### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by elmerehbi** [joepmoritz/MatlabFilenameAutoComplete#1]
Hello there,

I would like to install this plugin but it doesn't appear in the package manger.

How can I install it?

Thanks

**Comment by joepmoritz** [comment]
This is an addon for the Sublime Text editor, and should be installed using the package manager at https://packagecontrol.io/
It appears in my list just fine when I search for "matlab".

**Comment by elmerehbi** [comment]
I understand that and I rechecked it, still cannot find it.

**Comment by joepmoritz** [comment]
You can try installing it manually from Github by cloning the repo into Sublime's packages folder (see here: http://stackoverflow.com/questions/23026201/sublime-text-3-how-to-install-plugins-from-github).

Or you can try adding this github site as repository to Package control, described here: https://packagecontrol.io/docs/usage

**Comment by elmerehbi** [comment]
Thanks for the reply. Actually I didn't need to do this. I already had it installed so it didn't appear in the install list. Sorry for the inconvenience.
